platform: linux
image_resource:
  type: mock
  source: {mirror_self: true}

inputs:
- name: main
- name: dev

outputs:
- name: main
- name: dev

run:
  path: sh
  args:
  - -c
  - |
    ls -lah
    echo "creating versions"
    echo "hello-world" > main/version
    echo "hey there dev" > dev/version
