platform: linux

image_resource:
  type: mock
  source: { mirror_self: true }

params:
  ECHO_ME: "default text to echo from task config file"
  ALSO_ME:

run:
  path: sh
  args:
  - -c
  - |
    echo ${ECHO_ME} and ${ALSO_ME}
